version: '3.7'

services:
  web:
    build: ./hogarQuintillan
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hogarQuintillan/:/usr/src/hogarQuintillan/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev