# Generated by Django 3.0.4 on 2020-04-16 15:29

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=1000)),
                ('categoria', models.CharField(choices=[('pe', 'Personal'), ('ta', 'Laboral'), ('fa', 'Familiar')], max_length=2)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None)),
                ('cita', models.BooleanField(default=False)),
                ('fecha_cita', models.DateTimeField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_limite', models.DateTimeField(blank=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL)),
                ('dirigido', models.ManyToManyField(related_name='dirigido', to=settings.AUTH_USER_MODEL)),
                ('hijo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_hijo', to='memos.Memo')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo_padre', to='memos.Memo')),
            ],
        ),
    ]
