# Generated by Django 3.0.4 on 2020-04-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0003_auto_20200416_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='fecha_cita',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
