# Generated by Django 3.0.4 on 2020-04-16 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memos', '0004_auto_20200416_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memocreador', to=settings.AUTH_USER_MODEL),
        ),
    ]
