# Generated by Django 3.0.4 on 2020-04-17 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memos', '0005_auto_20200417_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='hijo',
        ),
        migrations.AlterField(
            model_name='memo',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memo',
            name='dirigido',
            field=models.ManyToManyField(related_name='memos_dirigidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memo',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='memos.Memo'),
        ),
    ]
