# Generated by Django 3.0.4 on 2020-04-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0010_auto_20200417_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memo',
            name='ignorar',
            field=models.BooleanField(default=False),
        ),
    ]
