# Generated by Django 3.0.4 on 2020-04-19 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memos', '0011_auto_20200417_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='prioridad',
            field=models.CharField(choices=[('al', 'Alta'), ('no', 'Normal'), ('ba', 'Baja')], default='no', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='categoria',
            field=models.CharField(choices=[('pe', 'Personal'), ('ta', 'Laboral'), ('fa', 'Familiar')], default='pe', max_length=2, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='cita',
            field=models.BooleanField(default=False, verbose_name='Cita'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='completada',
            field=models.BooleanField(default=False, verbose_name='Completada'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='detalle',
            field=models.TextField(max_length=1000, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='fecha_cita',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha cita'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha limite'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='ignorar',
            field=models.BooleanField(default=False, verbose_name='Ignorar'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
