# Generated by Django 3.0.4 on 2020-04-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0013_auto_20200420_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['prioridad', 'fecha_limite', 'fecha_creacion']},
        ),
    ]
