# Generated by Django 3.0.4 on 2020-04-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_ingrediente_ingredientereceta_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='ingredientereceta',
            name='recetas',
            field=models.ManyToManyField(blank=True, related_name='ingredientes', to='recetas.Receta'),
        ),
        migrations.AlterField(
            model_name='ingredientereceta',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente', to='recetas.Ingrediente'),
        ),
    ]
