# Generated by Django 3.0.4 on 2020-04-09 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_auto_20200409_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='tipoMedida',
            field=models.CharField(choices=[('gr', 'gramos'), ('ml', 'mililitros'), ('kg', 'kilogramos'), ('li', 'litros'), ('cu', 'cucharada'), ('ci', 'cucharadita')], max_length=64),
        ),
        migrations.AlterField(
            model_name='receta',
            name='dificultad',
            field=models.CharField(blank=True, choices=[('ri', 'Ridicula'), ('ba', 'Baja'), ('mo', 'Moderada'), ('di', 'Dificil'), ('md', 'Muy dificil'), ('in', 'Infernal')], max_length=64),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempoPreparacion',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=7200)),
        ),
    ]
