# Generated by Django 3.0.4 on 2020-04-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_auto_20200409_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='comensales',
            field=models.IntegerField(default=2),
        ),
    ]
