# Generated by Django 3.0.4 on 2020-04-09 14:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_auto_20200409_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='etiquetas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=24), default=list, size=None),
        ),
    ]
