# Generated by Django 3.0.4 on 2020-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0009_auto_20200410_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='tipoMedida',
            field=models.CharField(choices=[('gr', 'gramos'), ('ml', 'mililitros'), ('kg', 'kilogramos'), ('li', 'litros'), ('cu', 'cucharada'), ('ci', 'cucharadita'), ('ud', 'unidades'), ('pl', 'pellizco'), ('pu', 'puñado'), ('ma', 'manojo'), ('di', 'dientes'), ('ca', 'cabeza')], max_length=64),
        ),
    ]
