# Generated by Django 3.0.4 on 2020-04-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0010_auto_20200410_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientereceta',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_recetas', to='recetas.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='ingredientereceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_recetas', to='recetas.Receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='recetas.Categoria'),
        ),
    ]
