# Generated by Django 3.0.4 on 2020-04-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0011_auto_20200417_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(default='Maravillosas recetas de este estilo particular, ñam, ñam', max_length=500),
        ),
    ]
