# Generated by Django 3.0.4 on 2020-04-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0012_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
    ]
